use_frameworks!

target 'PulseAnimView_Example' do
  pod 'PulseAnimView', :path => '../'

  target 'PulseAnimView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
